
services:
  mysql:
    image: mysql:8.0
    container_name: shortener_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shortener_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:alpine
    container_name: shortener_redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: